### PR TITLE
Add resource path warning

### PR DESCRIPTION
**Pull request by circlingthesun**
Warn the user when `collection_path == path`. See #290

### CODE REVIEW

**Comment by ametaireau** [comment]
Thanks!

**Comment by ametaireau** [comment]
Can we add a test for this?

**Comment by circlingthesun** [comment]
Well, it's just a warning message. Would you prefer an exception instead?

**Comment by ametaireau** [comment]
A warning message is fine. But having a test exercising we're actually alerting the user make sense to me. Here is how we did in Cliquet for instance: https://github.com/mozilla-services/cliquet/blob/314b7518143a9f382880ca0e633db155aac8d0b9/cliquet/tests/test_initialization.py#L82-L96

**Comment by ametaireau** [comment]
@circlingthesun hey, just checking out if you have anything?

**Comment by circlingthesun** [comment]
Yep. I've added the test.

**Comment by ametaireau** [comment]
excellent! Thanks.

**Pull request merged**
